/**
 * Entity Manager - Core entity and relationship management system
 * Implements Task 5.8.4: Entity Interconnection Architecture
 */

const Database = require('better-sqlite3');
const path = require('path');

class EntityManager {
  constructor(dbPath) {
    this.db = new Database(dbPath || path.join(__dirname, 'database.db'));
    this.db.pragma('journal_mode = WAL');
    this.db.pragma('synchronous = NORMAL');
    this.db.pragma('foreign_keys = ON');
  }

  /**
   * Board-based ID generation system (JIRA-style)
   * Generates unique IDs like TASK-123, DASH-45, ISSUE-7
   */
  async generateEntityId(boardPrefix, entityType = null) {
    try {
      // Get board information and validate
      const board = this.db.prepare('SELECT * FROM boards WHERE prefix = ? AND is_active = 1').get(boardPrefix);
      if (!board) {
        throw new Error(`Board with prefix '${boardPrefix}' not found or not active`);
      }

      // Use provided entity type or board default
      const finalEntityType = entityType || board.default_entity_type;

      // Get next counter for this board
      const nextNum = (board.current_counter || 0) + 1;
      
      // Update counter in transaction
      const updateResult = this.db.prepare('UPDATE boards SET current_counter = ? WHERE prefix = ?')
        .run(nextNum, boardPrefix);

      if (updateResult.changes === 0) {
        throw new Error(`Failed to update counter for board ${boardPrefix}`);
      }
      
      const newId = `${boardPrefix}-${nextNum}`;
      console.log(`✅ Generated ID: ${newId} (type: ${finalEntityType})`);
      return newId;
      
    } catch (error) {
      console.error('Error generating entity ID:', error);
      // Fallback to timestamp-based ID
      const timestamp = Date.now().toString().slice(-6);
      const random = Math.random().toString(36).substr(2, 3);
      return `${boardPrefix}-${timestamp}-${random}`;
    }
  }

  /**
   * Create a new entity with proper hierarchy and relationships
   */
  async createEntity({
    entityType,
    title,
    description = '',
    parentId = null,
    boardPrefix = null,
    status = 'pending',
    priority = 'medium',
    assignee = null,
    estimatedHours = null,
    metadata = {},
    attributes = {},
    labels = [],
    dependencies = []
  }) {
    try {
      // Determine board prefix based on entity type if not provided
      if (!boardPrefix) {
        const boardMap = {
          'project': 'PROJ',
          'phase': 'PHASE', 
          'task': 'TASK',
          'subtask': 'TASK',
          'issue': 'ISSUE',
          'specification': 'SPEC',
          'quality_report': 'QUAL',
          'review': 'REV',
          'approval': 'REV'
        };
        boardPrefix = boardMap[entityType] || 'TASK';
      }

      // Generate unique ID
      const entityId = await this.generateEntityId(boardPrefix, entityType);

      // Calculate hierarchy information
      let level = 0;
      let hierarchyPath = entityId;
      let parentEntity = null;

      if (parentId) {
        parentEntity = this.db.prepare('SELECT * FROM entities WHERE id = ?').get(parentId);
        if (parentEntity) {
          level = parentEntity.level + 1;
          hierarchyPath = `${parentEntity.hierarchy_path}/${entityId}`;
        }
      }

      // Insert entity
      const insertEntity = this.db.prepare(`
        INSERT INTO entities (
          id, entity_type, parent_id, board_id, title, description,
          status, priority, level, hierarchy_path, assignee,
          estimated_hours, metadata, attributes, labels, dependencies,
          created_by, updated_by
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      const result = insertEntity.run(
        entityId,
        entityType,
        parentId,
        boardPrefix,
        title,
        description,
        status,
        priority,
        level,
        hierarchyPath,
        assignee,
        estimatedHours,
        JSON.stringify(metadata),
        JSON.stringify(attributes),
        JSON.stringify(labels),
        JSON.stringify(dependencies),
        'system', // created_by
        'system'  // updated_by
      );

      if (result.changes > 0) {
        console.log(`✅ Created entity: ${entityId} - ${title}`);
        
        // Auto-create parent-child relationship if parent exists
        if (parentId) {
          await this.createRelationship(parentId, entityId, 'parent_of', {
            strength: 1.0,
            isAutoGenerated: true
          });
        }

        return this.getEntity(entityId);
      } else {
        throw new Error('Failed to create entity');
      }

    } catch (error) {
      console.error('Error creating entity:', error);
      throw error;
    }
  }

  /**
   * Get entity by ID with full information
   */
  getEntity(entityId) {
    const entity = this.db.prepare(`
      SELECT *, 
        json_extract(metadata, '$') as metadata_obj,
        json_extract(attributes, '$') as attributes_obj,
        json_extract(labels, '$') as labels_array,
        json_extract(dependencies, '$') as dependencies_array
      FROM entities WHERE id = ?
    `).get(entityId);

    if (entity) {
      // Parse JSON fields
      entity.metadata = JSON.parse(entity.metadata || '{}');
      entity.attributes = JSON.parse(entity.attributes || '{}');
      entity.labels = JSON.parse(entity.labels || '[]');
      entity.dependencies = JSON.parse(entity.dependencies || '[]');
    }

    return entity;
  }

  /**
   * Get entity children (direct descendants)
   */
  getEntityChildren(entityId) {
    const children = this.db.prepare(`
      SELECT * FROM entities 
      WHERE parent_id = ? 
      ORDER BY sort_order, created_at
    `).all(entityId);

    return children.map(child => {
      child.metadata = JSON.parse(child.metadata || '{}');
      child.attributes = JSON.parse(child.attributes || '{}');
      child.labels = JSON.parse(child.labels || '[]');
      child.dependencies = JSON.parse(child.dependencies || '[]');
      return child;
    });
  }

  /**
   * Get entity hierarchy (all descendants)
   */
  getEntityHierarchy(entityId) {
    const descendants = this.db.prepare(`
      SELECT * FROM entities 
      WHERE hierarchy_path LIKE ? AND id != ?
      ORDER BY level, sort_order, created_at
    `).all(`%${entityId}%`, entityId);

    return descendants.map(entity => {
      entity.metadata = JSON.parse(entity.metadata || '{}');
      entity.attributes = JSON.parse(entity.attributes || '{}');
      entity.labels = JSON.parse(entity.labels || '[]');
      entity.dependencies = JSON.parse(entity.dependencies || '[]');
      return entity;
    });
  }

  /**
   * Create relationship between two entities
   */
  async createRelationship(sourceEntityId, targetEntityId, relationshipType, options = {}) {
    try {
      // Validate entities exist
      const sourceEntity = this.getEntity(sourceEntityId);
      const targetEntity = this.getEntity(targetEntityId);

      if (!sourceEntity || !targetEntity) {
        throw new Error('Source or target entity not found');
      }

      // Generate relationship ID
      const relationshipId = await this.generateEntityId('REL', 'relationship');

      // Create relationship
      const insertRelationship = this.db.prepare(`
        INSERT INTO entity_relationships (
          id, source_entity_id, target_entity_id, relationship_type,
          strength, is_auto_generated, impact_score, is_bidirectional,
          context, notes, created_by
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      const result = insertRelationship.run(
        relationshipId,
        sourceEntityId,
        targetEntityId,
        relationshipType,
        options.strength || 0.5,
        options.isAutoGenerated ? 1 : 0,
        options.impactScore || 0.5,
        options.isBidirectional ? 1 : 0,
        JSON.stringify(options.context || {}),
        options.notes || null,
        options.createdBy || 'system'
      );

      if (result.changes > 0) {
        console.log(`✅ Created relationship: ${sourceEntityId} -[${relationshipType}]-> ${targetEntityId}`);
        return relationshipId;
      } else {
        throw new Error('Failed to create relationship');
      }

    } catch (error) {
      console.error('Error creating relationship:', error);
      throw error;
    }
  }

  /**
   * Get entity relationships
   */
  getEntityRelationships(entityId, options = {}) {
    const { direction = 'both', relationshipType = null, isActive = true } = options;

    let query = `
      SELECT r.*, 
        se.title as source_title, se.entity_type as source_entity_type,
        te.title as target_title, te.entity_type as target_entity_type
      FROM entity_relationships r
      JOIN entities se ON r.source_entity_id = se.id
      JOIN entities te ON r.target_entity_id = te.id
      WHERE r.is_active = ?
    `;

    const params = [isActive ? 1 : 0];

    // Add direction filter
    if (direction === 'outgoing' || direction === 'both') {
      query += ` AND r.source_entity_id = ?`;
      params.push(entityId);
    }
    
    if (direction === 'incoming' || direction === 'both') {
      if (direction === 'both') {
        query = query.replace('AND r.source_entity_id = ?', 'AND (r.source_entity_id = ? OR r.target_entity_id = ?)');
        params.push(entityId);
      } else {
        query += ` AND r.target_entity_id = ?`;
        params.push(entityId);
      }
    }

    // Add relationship type filter
    if (relationshipType) {
      query += ` AND r.relationship_type = ?`;
      params.push(relationshipType);
    }

    query += ` ORDER BY r.created_at DESC`;

    const relationships = this.db.prepare(query).all(...params);

    return relationships.map(rel => {
      rel.context = JSON.parse(rel.context || '{}');
      rel.tags = JSON.parse(rel.tags || '[]');
      return rel;
    });
  }

  /**
   * Calculate real progress based on child completion
   */
  calculateEntityProgress(entityId) {
    const entity = this.getEntity(entityId);
    if (!entity) return 0;

    // If entity has no children, return current progress
    const children = this.getEntityChildren(entityId);
    if (children.length === 0) {
      return entity.progress || 0;
    }

    // Calculate weighted progress from children
    let totalProgress = 0;
    let totalWeight = 0;

    children.forEach(child => {
      const childProgress = this.calculateEntityProgress(child.id);
      const weight = child.estimated_hours || 1; // Use estimated hours as weight, default to 1
      
      totalProgress += childProgress * weight;
      totalWeight += weight;
    });

    const calculatedProgress = totalWeight > 0 ? Math.round(totalProgress / totalWeight) : 0;

    // Update entity progress in database
    this.db.prepare('UPDATE entities SET progress = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?')
      .run(calculatedProgress, entityId);

    return calculatedProgress;
  }

  /**
   * Update entity status and recalculate progress
   */
  updateEntityStatus(entityId, status, options = {}) {
    try {
      const updateFields = ['status = ?', 'updated_at = CURRENT_TIMESTAMP'];
      const params = [status];

      // Handle completion
      if (status === 'completed') {
        updateFields.push('completion_date = CURRENT_TIMESTAMP', 'progress = 100');
      }

      // Add optional fields
      if (options.progress !== undefined) {
        updateFields.push('progress = ?');
        params.push(options.progress);
      }

      if (options.assignee !== undefined) {
        updateFields.push('assignee = ?');
        params.push(options.assignee);
      }

      if (options.actualHours !== undefined) {
        updateFields.push('actual_hours = ?');
        params.push(options.actualHours);
      }

      params.push(entityId);

      const query = `UPDATE entities SET ${updateFields.join(', ')} WHERE id = ?`;
      const result = this.db.prepare(query).run(...params);

      if (result.changes > 0) {
        console.log(`✅ Updated entity ${entityId} status to ${status}`);
        
        // Recalculate parent progress
        const entity = this.getEntity(entityId);
        if (entity && entity.parent_id) {
          this.calculateEntityProgress(entity.parent_id);
        }

        return true;
      }

      return false;
    } catch (error) {
      console.error('Error updating entity status:', error);
      throw error;
    }
  }

  /**
   * Get board statistics
   */
  getBoardStats(boardPrefix) {
    const stats = this.db.prepare(`
      SELECT 
        COUNT(*) as total_entities,
        COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed,
        COUNT(CASE WHEN status = 'in_progress' THEN 1 END) as in_progress,
        COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending,
        COUNT(CASE WHEN status = 'blocked' THEN 1 END) as blocked,
        AVG(progress) as avg_progress,
        SUM(estimated_hours) as total_estimated_hours,
        SUM(actual_hours) as total_actual_hours
      FROM entities 
      WHERE board_id = ?
    `).get(boardPrefix);

    const board = this.db.prepare('SELECT * FROM boards WHERE prefix = ?').get(boardPrefix);

    return {
      board,
      ...stats,
      completion_rate: stats.total_entities > 0 ? (stats.completed / stats.total_entities * 100).toFixed(1) : 0
    };
  }

  /**
   * Search entities with advanced filters
   */
  searchEntities(searchOptions = {}) {
    let query = `
      SELECT e.*, 
        b.name as board_name,
        json_extract(metadata, '$') as metadata_obj,
        json_extract(attributes, '$') as attributes_obj
      FROM entities e
      JOIN boards b ON e.board_id = b.prefix
      WHERE 1=1
    `;
    
    const params = [];

    // Text search
    if (searchOptions.text) {
      query += ` AND (e.title LIKE ? OR e.description LIKE ?)`;
      const searchText = `%${searchOptions.text}%`;
      params.push(searchText, searchText);
    }

    // Entity type filter
    if (searchOptions.entityType) {
      query += ` AND e.entity_type = ?`;
      params.push(searchOptions.entityType);
    }

    // Status filter
    if (searchOptions.status) {
      query += ` AND e.status = ?`;
      params.push(searchOptions.status);
    }

    // Board filter
    if (searchOptions.boardPrefix) {
      query += ` AND e.board_id = ?`;
      params.push(searchOptions.boardPrefix);
    }

    // Assignee filter
    if (searchOptions.assignee) {
      query += ` AND e.assignee = ?`;
      params.push(searchOptions.assignee);
    }

    // Priority filter
    if (searchOptions.priority) {
      query += ` AND e.priority = ?`;
      params.push(searchOptions.priority);
    }

    query += ` ORDER BY e.updated_at DESC`;

    if (searchOptions.limit) {
      query += ` LIMIT ?`;
      params.push(searchOptions.limit);
    }

    const entities = this.db.prepare(query).all(...params);

    return entities.map(entity => {
      entity.metadata = JSON.parse(entity.metadata || '{}');
      entity.attributes = JSON.parse(entity.attributes || '{}');
      entity.labels = JSON.parse(entity.labels || '[]');
      entity.dependencies = JSON.parse(entity.dependencies || '[]');
      return entity;
    });
  }

  /**
   * Close database connection
   */
  close() {
    if (this.db) {
      this.db.close();
    }
  }
}

module.exports = EntityManager;